name: github_actions_oidc_test

on:
  push:

jobs:
  cdk_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::743530693495:role/GithubActionsOIDCTest'

      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - if: contains(github.event_name, 'push')
        run: npm i -g aws-cdk && npm i && cd apigw_lambda_s3_cf_route53 && cdk deploy --all