name: github_actions_cdk_deploy

on:
  push:

env:
  CUSTOM_DOMAIN: ${{secrets.CUSTOM_DOMAIN}}
  CERTIFICATE_ARN: ${{secrets.CERTIFICATE_ARN}}
  HOSTED_ZONE_ID: ${{secrets.HOSTED_ZONE_ID}}

jobs:
  cdk_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::743530693495:role/GithubActionsOIDCTest'

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install and deploy using CDK!!
        run: |
          npm install -g aws-cdk
          npm install -g pnpm
          cd apigw_lambda_s3_cf_route53
          pnpm install
          cdk deploy --all --require-approval never
